document.addEventListener("DOMContentLoaded", function (){
    //DOM Objects
    const playField = document.querySelector(".playField");
    const easyMode = document.querySelector(".lv1")
    const normalMode = document.querySelector(".lv2")
    const hardMode= document.querySelector(".lv3")
    const submit = document.querySelector(".Submit");
    const reset = document.querySelector(".reset");
    const submitButton = document.querySelector('.submitButton')
    let hiScore = document.querySelector('.hScore');
    let currentScore = document.querySelector('.cScore');
    let storedHiScore = localStorage.getItem('HiScore');

//GENERATE PLAY FIELD
    //Creates the Div for the game's buttons.
    function createBoard (ID) {
        return `
        <div class = "gameButton" data-id="${ID}">
        </div>`
    }
    //Simple loop function that creates an array of the gameButton divs
    function createGrid (num) {
        const board = [];
        for (let i = 0; i <= num; i++) {
        board.push(createBoard(i))
    }
    return board;
}
    //renderBoard is an array of objects that contains all 16 of the game buttons.
const renderBoard = createGrid(15);

    //Renders all the game buttons on the page by joining the array into string with \n
playField.innerHTML = renderBoard.join('\n');

    //Self invoked function to check if a hi score is stored in local memory and to render it in the appropriate score box if it is.
(function hiScoreCheck () {
    if (localStorage.getItem("HiScore") === null) {
        hiScore.textContent = `${0}`;
    } else {hiScore.textContent = storedHiScore;}
}());

//GAME PLAY FUNCTIONALITY
    // Generates a random sequence of game button inputs to start a game.
const playButtons = document.querySelectorAll(".gameButton");
let answer = [];
function generatePuzzle (difficulty, answer = []) {
    while(answer.length < difficulty){
        let random = Math.floor(Math.random()* 16)
        if(answer.indexOf(random) === -1){
            answer.push(random)    
        } 
    }
    return answer;
}
    //Function starts the gameplay sequence and takes starting list of buttons, difficulty, and time between flashes as parameters.
let startingDifficulty;
function play (puzzle, startingDiff, delayTime) {
    startingDifficulty = startingDiff;
    let inputs = Array.from(playButtons);
    delay(puzzle.length -1, delayTime, showPuzzle(puzzle, inputs), clearBoard);
}

    // Starts a Game on the Easy difficulty setting
function playEasy () {
    answer = generatePuzzle(4);
    clearBoard();
    play(answer, 10, 1500);
    normalMode.disabled = true;
    hardMode.disabled = true;
}

    //Starts a Game on the Easy difficulty setting
function playMedium () {
    answer = generatePuzzle(5);
    easyMode.disabled = true;
    hardMode.disabled = true;
    clearBoard();
    play(answer, 25, 1200);
}

    //Starts a Game on the Easy difficulty setting
function playHard () {
    answer = generatePuzzle(6);
    easyMode.disabled = true;
    normalMode.disabled = true;
    clearBoard();
    play(answer, 50, 800);
}

    //removes all css classes that effect the background color from the game buttons.
function clearBoard(){
    const inputs = Array.from(playButtons);
    inputs.forEach(ele => ele.classList.remove('highlighted'));
    inputs.forEach(ele => ele.classList.remove('selected'));
}

    //Increments the length of the answer array by one assuming all game buttons haven't already been called.
function playNextRound() {
    const inputs = Array.from(playButtons);
    if (answer.length < 16) {
        answer = generatePuzzle(answer.length +1, answer)
    }
    submission = [];
    inputs.forEach(ele => ele.classList.remove('selected'));
    submit.textContent = `SUBMIT`;
    play(answer, 10, 1500);
}

    //Adds the highlighted class to the answer buttons so user knows what buttons to press.
function showPuzzle (answer,inputs) {
    let index = 0
    return function(){
        inputs[answer[index]].classList.add('highlighted')
        index++
    }
}
    //Function produces the delay between buttons appearing on screen during gameplay.
function delay(numberOfTimes, milliseconds, cb, lastAction){
    if(numberOfTimes < 0) return setTimeout(lastAction,milliseconds)
    setTimeout(function(){
        cb()
        delay(numberOfTimes -1, milliseconds, cb, lastAction)
    },milliseconds)
}

// ANSWER CHECKING & Scoring
    //Adds the data-ids of the buttons the user presses to repeat the pattern to a submission array.
let submission = [];
function inputAnswer(event) {
    submission.push(event.target.getAttribute('data-id'));
    event.target.classList.add("selected");
}
    //Function checks whether the submission array exactly matches the answer array generated by the computer and either continues or ends the game accordingly.
function checkAnswer() {
    let hiScoreVal = Number(hiScore.textContent);
    if (answer.length !== submission.length) {
        submit.textContent = `Sorry Try Again`;
        localStorage.setItem("HiScore", hiScoreVal);
        setTimeout(resetGame, 1500)
    }
    if (arrayCheck(answer, submission)) {
        submit.textContent=`Correct`;
        updateScores(startingDifficulty);
        if(submission.length >= 16) {
            submit.textContent = `WOW You Beat The Game, Congratulations!!!`;
            setTimeout(resetGame, 1500);
        }
        setTimeout(playNextRound, 1500);
    } else {
        submit.textContent = `Sorry Try Again`;
        localStorage.setItem("HiScore", hiScoreVal);
        setTimeout(resetGame, 1500);
    }
}
    //Verifies that the contents of the answer and submission arrays are identical.
function arrayCheck (arr1, arr2) {
    return arr1.toString() === arr2.toString();
}
    // Resets all the arrays and buttons in the game back to their original starting values.
function resetGame () {
    const inputs = Array.from(playButtons);
    answer = [];
    submission = [];
    currentScore.textContent = `${0}`;
    inputs.forEach(ele => ele.classList.remove('selected'));
    submit.textContent = `SUBMIT`;
    easyMode.disabled = false;
    normalMode.disabled = false;
    hardMode.disabled = false;
}
    //Takes in the difficulty level being played and updates your score as you continue to play the game.
function updateScores (difficulty) {
    let hiScoreVal = Number(hiScore.textContent);
    let scoreVal = Number(currentScore.textContent);
    scoreVal += scoreVal + (answer.length * difficulty)
    currentScore.textContent= `${scoreVal}`;
    if (scoreVal > hiScoreVal) {
        hiScore.textContent = `${scoreVal}`;
        localStorage.setItem("HiScore", scoreVal);
    }
}
//EVENT LISTENERs
playButtons.forEach(cell => cell.addEventListener("mouseover", function(){
    cell.classList.add('hover');
}));
playButtons.forEach(cell => cell.addEventListener("mouseout", function() {
    cell.classList.remove('hover')
}));
playButtons.forEach(cell => cell.addEventListener("click", inputAnswer));
easyMode.addEventListener('click', playEasy);
normalMode.addEventListener('click', playMedium);
hardMode.addEventListener('click', playHard);
submit.addEventListener('click', checkAnswer);
submitButton.addEventListener('mouseover', function (){
    submitButton.classList.add('emphasize')
});
submitButton.addEventListener('mouseout', function (){
    submitButton.classList.remove('emphasize')
});
reset.addEventListener('click', resetGame);
})